<template>
  <div class="">
    <div v-for="post in posts" :key="post.id" class="m-1">
      <BPostItem :post="post" />
    </div>
  </div>
</template>

<script>
import BPostItem from "@/components/post/BPostItem.vue";

export default {
  name: "BPost",
  data() {
    return {
      posts: [
        {
          id: 1,
          category_id: 3,
          title: "Tempore.",
          description: "Nesciunt et quo hic.",
          content:
            "Sit autem quisquam asperiores. Ad optio facilis illum doloremque reiciendis cumque. Dolores rerum qui voluptatem est voluptate est quisquam. Aspernatur maxime voluptatem libero nostrum. Deserunt nesciunt quis qui tenetur autem qui. Eaque facere quisquam enim qui et omnis. Dolores debitis labore rerum veniam fuga deserunt. Maxime laudantium libero qui. Architecto eos dolorem deleniti quia asperiores quos. Fugit doloremque odio a doloremque.",
          published: 1,
          date_publication: "2023-03-03 16:27:17",
          likes: 820,
          dislikes: 232,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 3,
            name: "rerum",
            parent_id: null,
          },
        },
        {
          id: 2,
          category_id: 26,
          title: "Sit.",
          description: "Totam esse alias.",
          content:
            "A ut illo et eos aut excepturi. Asperiores est voluptatem facere non ea ullam maiores explicabo. Ex sapiente ipsum nulla provident impedit consequatur labore. Alias et dolorum voluptatem aliquam eaque minima eligendi.",
          published: 0,
          date_publication: "2023-02-23 16:27:17",
          likes: 333,
          dislikes: 748,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 26,
            name: "tenetur",
            parent_id: 5,
          },
        },
        {
          id: 3,
          category_id: 22,
          title: "Ex.",
          description: "Deserunt a et.",
          content:
            "Voluptatem aut rerum perferendis in autem. Qui est quos occaecati tenetur. Nostrum culpa consequatur aperiam ea. Velit et omnis impedit eaque necessitatibus.",
          published: 0,
          date_publication: "2023-03-08 16:27:17",
          likes: 553,
          dislikes: 907,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 22,
            name: "iure",
            parent_id: 5,
          },
        },
        {
          id: 4,
          category_id: 18,
          title: "Eum.",
          description: "Dolores aut.",
          content:
            "Eligendi voluptates qui optio sint ullam. Sunt et culpa earum quia aut cum error incidunt. Voluptatum officiis illum odio non quis saepe rerum. Necessitatibus et doloremque velit ratione. Omnis dolor odio qui in totam quasi. Sapiente molestiae numquam ea et ut sunt est. Pariatur sapiente fuga quos et velit sint. Doloremque nulla eum est est. Modi excepturi praesentium laborum accusamus. Omnis ab rerum temporibus.",
          published: 1,
          date_publication: "2023-02-28 16:27:17",
          likes: 846,
          dislikes: 208,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 18,
            name: "expedita",
            parent_id: 4,
          },
        },
        {
          id: 5,
          category_id: 23,
          title: "Error.",
          description: "Qui sunt voluptas.",
          content:
            "Animi possimus illo doloribus aspernatur dolorum sunt. Dolorem repellendus est eveniet quidem. Asperiores dignissimos suscipit officia dolorem tempore quos. Consequatur enim et consectetur placeat placeat molestiae porro rerum.",
          published: 0,
          date_publication: "2023-02-22 16:27:17",
          likes: 712,
          dislikes: 482,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 23,
            name: "nesciunt",
            parent_id: 5,
          },
        },
        {
          id: 6,
          category_id: 2,
          title: "Error.",
          description: "Quia eos esse quo.",
          content:
            "Quis eos mollitia dolor numquam. Qui quibusdam nobis rerum eos nihil omnis sed similique. Labore illum minima et delectus sit iure porro ut. Molestiae at voluptatem consequatur quidem odio perspiciatis quod. Eius ex quam assumenda cupiditate.",
          published: 0,
          date_publication: "2023-02-27 16:27:17",
          likes: 118,
          dislikes: 179,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 2,
            name: "ut",
            parent_id: null,
          },
        },
        {
          id: 7,
          category_id: 21,
          title: "Ut.",
          description: "Velit ut et optio.",
          content:
            "Consequatur aliquam alias accusantium exercitationem unde consequuntur sint ducimus. Veniam culpa soluta deleniti porro aut. Repellendus quos id molestiae magni animi reprehenderit odio. Dolore maxime voluptatem est labore vel facilis.",
          published: 0,
          date_publication: "2023-02-23 16:27:17",
          likes: 409,
          dislikes: 960,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 21,
            name: "fugiat",
            parent_id: 4,
          },
        },
        {
          id: 8,
          category_id: 1,
          title: "Ab.",
          description: "Perspiciatis ut.",
          content:
            "Molestiae sunt qui quis facilis. Voluptatem repellendus suscipit consectetur voluptatem voluptate. Magnam deleniti alias sunt veniam explicabo assumenda. Est aut molestiae veritatis molestias. Asperiores aliquid molestiae rem ut vero minus praesentium. Repellendus sint qui deserunt tempore ea fugit quidem doloremque. Ducimus et natus in impedit. Architecto ut ad illum id culpa.",
          published: 0,
          date_publication: "2023-03-06 16:27:17",
          likes: 587,
          dislikes: 439,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
        {
          id: 9,
          category_id: 14,
          title: "Ullam.",
          description: "Ut amet unde.",
          content:
            "Voluptate optio corporis id nesciunt totam. Dolore saepe autem est optio commodi eos quasi. In fugit unde aliquid. Veniam amet inventore qui assumenda enim consequuntur. Et suscipit id quia quod temporibus sit. Ut animi rem aut et quasi quasi. Ipsa repudiandae accusamus nemo nihil ut. Voluptatem et molestias vel. Architecto ex eius recusandae sed. Nisi qui culpa voluptatem magnam.",
          published: 1,
          date_publication: "2023-03-04 16:27:17",
          likes: 764,
          dislikes: 633,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 14,
            name: "quia",
            parent_id: 3,
          },
        },
        {
          id: 10,
          category_id: 10,
          title: "Sit.",
          description: "In nihil sit neque.",
          content:
            "Explicabo quos quo veniam fugit vitae aut enim. Sit expedita consequatur error debitis debitis sit. Aspernatur sed expedita et fugit voluptatem et dolore. Rem enim inventore qui assumenda et rerum aut. Sit doloremque unde doloremque. Similique nisi ex sunt voluptatibus minima. Libero suscipit occaecati sunt rerum commodi. Debitis nisi delectus aut et mollitia laudantium. Eligendi aut rerum ullam itaque consectetur animi et.",
          published: 1,
          date_publication: "2023-03-03 16:27:17",
          likes: 859,
          dislikes: 565,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 10,
            name: "ipsam",
            parent_id: null,
          },
        },
        {
          id: 11,
          category_id: 26,
          title: "Aut sed.",
          description: "Fugit nulla maiores.",
          content:
            "Ipsum quasi expedita aliquid asperiores asperiores facere. Cum voluptatem in sed tempore ipsum qui. Id nobis voluptatem maxime ex dolores. Aperiam molestias natus consequatur. Quibusdam magnam delectus velit autem molestias. Minus soluta nihil neque quaerat aut.",
          published: 0,
          date_publication: "2023-02-25 16:27:17",
          likes: 613,
          dislikes: 847,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 26,
            name: "tenetur",
            parent_id: 5,
          },
        },
        {
          id: 12,
          category_id: 1,
          title: "Cumque.",
          description: "Aut at eum.",
          content:
            "Ea est aut vero est fuga nemo neque odit. Explicabo error vero temporibus doloribus. Culpa veritatis corporis quisquam. Dolores reiciendis ex ullam consequatur iste nulla id. Aut ipsam repellat maxime unde amet quis. Et aliquam quia illum aut veritatis. Et in sit ut nobis explicabo. Ipsum qui hic eos fugiat vel est suscipit. Nihil quae accusamus asperiores ut sed.",
          published: 1,
          date_publication: "2023-02-24 16:27:17",
          likes: 819,
          dislikes: 946,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
        {
          id: 13,
          category_id: 4,
          title: "Et illum.",
          description: "Ab animi illo et.",
          content:
            "Voluptatem repellat velit voluptate corporis ut repellendus quo. Et minus repellat et delectus libero id. Labore ex non nihil praesentium quas. Quam aperiam commodi ex enim unde eligendi aut. Veniam sit modi enim consequatur. Ut velit aspernatur fugiat necessitatibus blanditiis atque asperiores. Qui ipsam est officiis.",
          published: 1,
          date_publication: "2023-03-06 16:27:17",
          likes: 970,
          dislikes: 314,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 4,
            name: "enim",
            parent_id: null,
          },
        },
        {
          id: 14,
          category_id: 18,
          title: "Aut.",
          description: "Pariatur quo vel.",
          content:
            "Rerum est consequuntur placeat maxime ducimus et. Enim sapiente laudantium id nobis. Et inventore porro et unde eius. Et aut et occaecati quo maxime. A eaque iusto esse nihil quis. Fuga optio sit facere ab nam. Deserunt et fugiat minus laudantium possimus. Officiis minus quas quia. Et quia optio quam quaerat excepturi.",
          published: 1,
          date_publication: "2023-02-26 16:27:17",
          likes: 336,
          dislikes: 909,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 18,
            name: "expedita",
            parent_id: 4,
          },
        },
        {
          id: 15,
          category_id: 14,
          title: "Aut.",
          description: "Placeat dolorum.",
          content:
            "Qui vero possimus consectetur cumque id veniam. Aspernatur numquam unde qui eaque. Totam architecto sapiente error nesciunt. Eum facilis rem vel natus quam mollitia consectetur dolore.",
          published: 1,
          date_publication: "2023-02-23 16:27:17",
          likes: 825,
          dislikes: 169,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 14,
            name: "quia",
            parent_id: 3,
          },
        },
        {
          id: 16,
          category_id: 26,
          title: "Cum.",
          description: "Fuga amet.",
          content:
            "Tenetur aut numquam corporis quaerat eos in. Laboriosam ut qui iure cumque nihil debitis. Praesentium molestiae amet qui quia mollitia autem. Minus provident repellat rerum repellat. Iste earum sit eos qui id quo. Temporibus vero ut quia molestias.",
          published: 1,
          date_publication: "2023-03-04 16:27:17",
          likes: 877,
          dislikes: 964,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 26,
            name: "tenetur",
            parent_id: 5,
          },
        },
        {
          id: 17,
          category_id: 2,
          title: "Dolor.",
          description: "Corporis aliquam.",
          content:
            "Eum harum sint accusantium quae aut. Iste vitae nisi molestias fuga qui expedita. Eligendi ut at reprehenderit quia ut. Vel ipsam veritatis sint a quaerat maiores quia sit. Delectus necessitatibus nobis ea libero. Culpa ipsum ea ab qui molestias at consectetur. Sit omnis quam quia voluptatem occaecati.",
          published: 1,
          date_publication: "2023-02-25 16:27:17",
          likes: 287,
          dislikes: 264,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 2,
            name: "ut",
            parent_id: null,
          },
        },
        {
          id: 18,
          category_id: 20,
          title: "Cum.",
          description: "Accusamus eum.",
          content:
            "Placeat occaecati et dolores reprehenderit dolores. Ad quia est minima fugiat amet. Ex enim in tenetur repellat enim et quia debitis. Perferendis omnis voluptatum deleniti non dolorem facilis dolores. Quia perferendis dolorum aut qui voluptas soluta. Et placeat quaerat quae optio sunt molestiae nesciunt.",
          published: 0,
          date_publication: "2023-02-27 16:27:17",
          likes: 497,
          dislikes: 212,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 20,
            name: "ut",
            parent_id: 4,
          },
        },
        {
          id: 19,
          category_id: 26,
          title: "Et.",
          description: "Et quaerat non.",
          content:
            "Ut voluptatum quia vitae eos maiores consectetur. Fugiat velit voluptates laboriosam eaque reprehenderit. Quam non et quam ab pariatur sint a sunt. Cum dicta iusto veniam non quas. Sed animi consequatur quibusdam natus. Vel itaque qui quia natus ut quaerat. Corporis est sint sint ex et. Quasi totam voluptas cumque tempore. Est odio et voluptatem voluptas quia hic laborum. Totam labore ducimus voluptas corrupti.",
          published: 1,
          date_publication: "2023-03-06 16:27:17",
          likes: 578,
          dislikes: 712,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 26,
            name: "tenetur",
            parent_id: 5,
          },
        },
        {
          id: 20,
          category_id: 26,
          title: "Quae.",
          description: "Et et quo sit.",
          content:
            "Beatae repudiandae magnam id et beatae reprehenderit ut. Est voluptatum quis saepe aspernatur qui. Omnis dicta alias vitae ratione. Consequatur voluptate sit aliquam harum. Excepturi reiciendis autem quo. Quasi non quibusdam inventore. Dignissimos molestiae tempora dolore iusto.",
          published: 0,
          date_publication: "2023-02-24 16:27:17",
          likes: 352,
          dislikes: 175,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 26,
            name: "tenetur",
            parent_id: 5,
          },
        },
        {
          id: 21,
          category_id: 10,
          title: "Illum.",
          description: "Atque consequatur.",
          content:
            "Porro beatae modi atque molestiae. Voluptatem nulla quos accusantium rerum velit est natus mollitia. Repellendus voluptates est earum nihil quod ea qui. Non autem animi perspiciatis quam neque facilis sapiente.",
          published: 1,
          date_publication: "2023-03-08 16:27:17",
          likes: 756,
          dislikes: 172,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 10,
            name: "ipsam",
            parent_id: null,
          },
        },
        {
          id: 22,
          category_id: 20,
          title: "Itaque.",
          description: "Eligendi quo ipsum.",
          content:
            "Consequatur et ut ullam a commodi maxime. Rerum non eum laborum eaque. Autem repellendus maxime laborum nisi aut id vel. Occaecati minima porro hic rem et. Quo dolorem et est. Ipsam voluptatem sequi consequatur. Cum qui a dolor laborum nam. Iure est voluptatibus dolores vitae voluptas nam officiis iste.",
          published: 1,
          date_publication: "2023-02-22 16:27:17",
          likes: 553,
          dislikes: 591,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 20,
            name: "ut",
            parent_id: 4,
          },
        },
        {
          id: 23,
          category_id: 11,
          title: "Totam.",
          description: "Qui dolorem et.",
          content:
            "Id et vel ratione voluptate. Vel nemo ducimus quo enim illum. Illum enim autem est rerum possimus at. Dolor quisquam in vitae tempora. Facilis dolorum fugit necessitatibus placeat numquam. Temporibus dolor odio optio perspiciatis. Aliquid ratione cumque itaque.",
          published: 0,
          date_publication: "2023-03-04 16:27:17",
          likes: 587,
          dislikes: 178,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 11,
            name: "aperiam",
            parent_id: 3,
          },
        },
        {
          id: 24,
          category_id: 24,
          title: "Voluptas.",
          description: "Vel est a et.",
          content:
            "Qui cum ducimus perspiciatis fuga et ut. Harum ut voluptas quia quo dolore id ab. Laudantium pariatur eligendi aut debitis. Officiis distinctio et sapiente quia. Et at et suscipit autem. Eum aliquid maxime officia culpa ea similique sunt. Et architecto voluptate vel aperiam reprehenderit nihil. Enim velit omnis molestias aliquid illum magnam.",
          published: 0,
          date_publication: "2023-02-23 16:27:17",
          likes: 568,
          dislikes: 529,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 24,
            name: "architecto",
            parent_id: 5,
          },
        },
        {
          id: 25,
          category_id: 25,
          title: "Nulla.",
          description: "Ullam temporibus.",
          content:
            "Eaque sit illum minus mollitia perspiciatis sint voluptatibus. Fugiat asperiores sint ipsam aut quam. Qui et quia deserunt est laborum.",
          published: 0,
          date_publication: "2023-02-22 16:27:17",
          likes: 576,
          dislikes: 431,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 25,
            name: "fugiat",
            parent_id: 5,
          },
        },
        {
          id: 26,
          category_id: 1,
          title: "Et.",
          description: "Dolorum sit.",
          content:
            "Assumenda optio illum qui. Odio qui explicabo placeat magnam modi qui ut voluptatem. Vel consequatur accusamus et maxime. Ipsum aut nihil atque qui ab. Veritatis et qui rerum illum ut. Quibusdam odio earum perferendis consequatur a soluta sint. Eius eius cumque id dolore ex.",
          published: 1,
          date_publication: "2023-03-08 16:27:17",
          likes: 444,
          dislikes: 157,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
        {
          id: 27,
          category_id: 8,
          title: "Eum vel.",
          description: "Tempora ullam et.",
          content:
            "Illo possimus ut dolorem officia facilis dolorem. Fuga officiis qui distinctio. Aut optio illum quos vitae illo ut ipsa. In qui omnis sed fugiat aut quod occaecati. Hic nesciunt est aut dignissimos reprehenderit molestiae. Vel at eveniet est ipsam consequatur libero. Ut provident explicabo et id dicta et. Iusto alias culpa laudantium eligendi distinctio optio et.",
          published: 0,
          date_publication: "2023-02-24 16:27:17",
          likes: 967,
          dislikes: 304,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 8,
            name: "eum",
            parent_id: null,
          },
        },
        {
          id: 28,
          category_id: 12,
          title: "Rerum.",
          description: "Sed debitis ab et.",
          content:
            "Iure ut et est quia. Pariatur eius provident sit. Molestiae dolorem voluptas et illum enim. Deleniti nulla autem aliquid. Ipsum distinctio quia debitis dignissimos. Sed accusamus sapiente corporis dolor. Molestias reprehenderit voluptas nobis perferendis qui.",
          published: 0,
          date_publication: "2023-03-03 16:27:17",
          likes: 856,
          dislikes: 449,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 12,
            name: "suscipit",
            parent_id: 3,
          },
        },
        {
          id: 29,
          category_id: 14,
          title: "Impedit.",
          description: "Ducimus officiis.",
          content:
            "Labore repellat quia dolorum sunt necessitatibus et quae. Veniam rerum est quis. Eaque iusto molestiae et voluptas maxime unde. Accusamus quis odio sint quia accusantium. Nobis necessitatibus nesciunt eius deleniti. Impedit deleniti commodi et voluptatem sunt. Sit atque et nam quidem molestiae commodi aspernatur. Inventore sit cupiditate dolorum deserunt aliquam sed provident. Repudiandae id ex dolores. Est aut rerum amet qui aut rerum.",
          published: 1,
          date_publication: "2023-02-22 16:27:17",
          likes: 354,
          dislikes: 471,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 14,
            name: "quia",
            parent_id: 3,
          },
        },
        {
          id: 30,
          category_id: 6,
          title: "Omnis.",
          description: "Suscipit repellat.",
          content:
            "Ut nemo rerum ad harum iste officia. Nihil aliquam doloremque quia iste laborum. Dignissimos facere explicabo dolore voluptatum quasi est voluptas ea. Nam omnis omnis magnam voluptas libero.",
          published: 0,
          date_publication: "2023-03-07 16:27:17",
          likes: 716,
          dislikes: 358,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 6,
            name: "quasi",
            parent_id: null,
          },
        },
        {
          id: 31,
          category_id: 2,
          title: "Amet.",
          description: "Odit corrupti.",
          content:
            "Illum est neque voluptatem non. Qui magni dolores voluptatem. Optio dicta vel sed sit blanditiis. Maxime non earum illum sint. Ut odit voluptatem tenetur iste autem. A vel alias omnis aut dolorem sint. Officia maxime fugiat et tenetur harum iure id placeat. Occaecati dolorem alias est. Voluptates quam est quis voluptatem aut. Enim accusantium esse aut non eos numquam magni soluta.",
          published: 1,
          date_publication: "2023-03-05 16:27:17",
          likes: 448,
          dislikes: 917,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 2,
            name: "ut",
            parent_id: null,
          },
        },
        {
          id: 32,
          category_id: 23,
          title: "Quia.",
          description: "Dolores magnam.",
          content:
            "Pariatur sunt adipisci qui animi eos aut. Ipsum eaque similique delectus possimus ea sed. Sint aut nisi perferendis dolorem.",
          published: 1,
          date_publication: "2023-03-01 16:27:17",
          likes: 304,
          dislikes: 336,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 23,
            name: "nesciunt",
            parent_id: 5,
          },
        },
        {
          id: 33,
          category_id: 16,
          title: "Rerum.",
          description: "Officiis est.",
          content:
            "Dignissimos laborum hic ullam velit eum tenetur quia nihil. Eaque itaque omnis non ducimus et voluptates. Nam qui nemo ea architecto est. Et eligendi quis numquam reprehenderit aut. Neque cumque iure nihil vero exercitationem. Voluptas similique quia quis quia error. Ut sunt quia ullam officiis culpa voluptatem nostrum. Alias est maiores cum impedit.",
          published: 1,
          date_publication: "2023-03-05 16:27:17",
          likes: 403,
          dislikes: 503,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 16,
            name: "tempore",
            parent_id: 3,
          },
        },
        {
          id: 34,
          category_id: 8,
          title: "Cum.",
          description: "Quod ipsam esse.",
          content:
            "Sunt et eligendi quia voluptatem quibusdam. Iure magni atque sed vitae modi rem. Rem commodi sit et sit ex. Nihil iure est inventore earum harum adipisci dolor. Cupiditate illo iusto vel omnis omnis. Ut consequatur quibusdam quae vel quod aliquam. In vero quasi vel distinctio. Vero quia omnis eum nobis quaerat nihil ratione. Iste est magni beatae commodi quisquam doloremque et voluptate.",
          published: 1,
          date_publication: "2023-03-04 16:27:17",
          likes: 913,
          dislikes: 457,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 8,
            name: "eum",
            parent_id: null,
          },
        },
        {
          id: 35,
          category_id: 1,
          title: "Sequi.",
          description: "Qui voluptates.",
          content:
            "Non amet debitis minus dolor. Vero ut nam voluptas velit quos in repellendus. Perspiciatis dignissimos quibusdam cumque consequuntur. Voluptas nisi amet quasi aperiam illo soluta et. Rerum quia tempore libero enim dicta.",
          published: 1,
          date_publication: "2023-02-25 16:27:17",
          likes: 472,
          dislikes: 163,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
        {
          id: 36,
          category_id: 12,
          title: "Odit.",
          description: "Similique et.",
          content:
            "Cumque voluptatem nemo iusto autem dicta ea provident. Vel exercitationem ipsam possimus officiis a. Fugit sunt voluptatibus a soluta. Non omnis possimus nostrum est amet veniam officiis corrupti. Consequatur sit itaque illum tenetur officiis ut ad. Dolorem dolorem consequatur vel. Consequatur ut numquam officia porro sint. Sit inventore et deserunt.",
          published: 1,
          date_publication: "2023-02-24 16:27:17",
          likes: 219,
          dislikes: 339,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 12,
            name: "suscipit",
            parent_id: 3,
          },
        },
        {
          id: 37,
          category_id: 12,
          title: "Qui qui.",
          description: "Minima quibusdam.",
          content:
            "Illum blanditiis corporis sint. Dolor ipsum repudiandae et nihil et. Praesentium ipsam ut sed placeat ut rerum tempore. Autem quod rerum nihil aut aut voluptas. Possimus aut sequi vel eos culpa. Aut molestiae est perferendis corporis et sint impedit.",
          published: 0,
          date_publication: "2023-02-24 16:27:17",
          likes: 118,
          dislikes: 653,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 12,
            name: "suscipit",
            parent_id: 3,
          },
        },
        {
          id: 38,
          category_id: 22,
          title: "Odio.",
          description: "Cumque asperiores.",
          content:
            "Ipsa aut enim quis deserunt. Sed quia dolorem quod cum. Dolor repudiandae magni et molestiae sapiente vero rerum. Est consequatur fugit qui odit quam molestias iusto. Aut voluptas sint expedita architecto similique. Eaque amet asperiores suscipit ut velit voluptatem ut. Aspernatur quia sed omnis eaque. Amet voluptates minima aspernatur iste mollitia. Accusantium accusamus omnis labore aut asperiores.",
          published: 1,
          date_publication: "2023-02-22 16:27:17",
          likes: 969,
          dislikes: 828,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 22,
            name: "iure",
            parent_id: 5,
          },
        },
        {
          id: 39,
          category_id: 8,
          title: "Eos qui.",
          description: "Dolor qui velit et.",
          content:
            "Similique qui et voluptatibus molestias cumque. Repellat quia magni quibusdam. Vel dolorem delectus non sapiente recusandae libero reiciendis. Quasi eveniet est voluptates. Et velit expedita officia odit labore et eos. Enim quia maiores nisi deserunt omnis. Cupiditate ex aut sed quia dolor. Quo vitae aut facere sed. Sit aut incidunt ipsa necessitatibus.",
          published: 0,
          date_publication: "2023-02-25 16:27:17",
          likes: 882,
          dislikes: 757,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 8,
            name: "eum",
            parent_id: null,
          },
        },
        {
          id: 40,
          category_id: 27,
          title: "Eos.",
          description: "Beatae ad ea qui.",
          content:
            "Nihil et debitis qui aut minus laborum. Dolore ut fuga enim totam sunt aliquid. Doloremque saepe omnis eveniet necessitatibus molestias voluptatem quaerat. Maiores exercitationem expedita occaecati assumenda. Molestias earum delectus veritatis. Nihil rerum iusto repellat cumque velit autem quos. Ea voluptatem in fugiat necessitatibus maxime voluptatem tempora. Adipisci voluptatem est et voluptates aliquam alias pariatur.",
          published: 1,
          date_publication: "2023-02-26 16:27:17",
          likes: 809,
          dislikes: 259,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 27,
            name: "vel",
            parent_id: 5,
          },
        },
        {
          id: 41,
          category_id: 18,
          title: "Est.",
          description: "Provident deleniti.",
          content:
            "Perspiciatis nostrum laboriosam rerum. Ullam sint ut beatae. Maxime ab officiis voluptatem aspernatur sapiente. Eius laudantium in quo error. Suscipit voluptates omnis beatae enim quae recusandae voluptatem aut. Et et nesciunt fugiat voluptatum qui rerum.",
          published: 0,
          date_publication: "2023-02-28 16:27:17",
          likes: 211,
          dislikes: 455,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 18,
            name: "expedita",
            parent_id: 4,
          },
        },
        {
          id: 42,
          category_id: 27,
          title: "Ea iste.",
          description: "Porro cumque eos.",
          content:
            "Fuga corrupti ipsa distinctio totam asperiores. Consequatur placeat est vero facere. Voluptatem odit facilis alias laudantium minus doloribus dolor aut. Quis cum labore sit et dolorum consectetur dolore voluptas. Distinctio commodi minus repudiandae omnis. Sed eaque qui et doloribus. Est asperiores maiores quis quam commodi dolores.",
          published: 0,
          date_publication: "2023-03-06 16:27:17",
          likes: 937,
          dislikes: 797,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 27,
            name: "vel",
            parent_id: 5,
          },
        },
        {
          id: 43,
          category_id: 5,
          title: "Quaerat.",
          description: "Quis dolor hic.",
          content:
            "Qui quo est occaecati ut sint totam pariatur sint. Fugit qui qui molestiae quasi adipisci. Veritatis ducimus quo est assumenda. Porro labore et sunt. Enim ut aut aut minus. Ad repudiandae ipsum deserunt in doloribus distinctio est. Cupiditate qui repellat assumenda quam. Magni dolores voluptas aut ut dolore id autem ad. Repellendus maxime corrupti voluptates sit aperiam cupiditate odio est.",
          published: 0,
          date_publication: "2023-02-28 16:27:17",
          likes: 750,
          dislikes: 951,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 5,
            name: "itaque",
            parent_id: null,
          },
        },
        {
          id: 44,
          category_id: 14,
          title: "Rerum.",
          description: "Soluta quaerat est.",
          content:
            "At quos ut autem est. Veniam aliquid culpa commodi. Ex quis quibusdam enim tempore consequatur sed et. Molestiae est nulla enim reprehenderit. Maxime ut sunt in omnis aut recusandae mollitia. Voluptas sit natus ut corrupti. A dignissimos et voluptatem impedit aut.",
          published: 1,
          date_publication: "2023-03-04 16:27:17",
          likes: 875,
          dislikes: 314,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 14,
            name: "quia",
            parent_id: 3,
          },
        },
        {
          id: 45,
          category_id: 21,
          title: "Error.",
          description: "Ipsum neque odio ad.",
          content:
            "Autem qui perspiciatis recusandae est nulla. Magnam iste et aut cumque quo voluptatem. Odit illo excepturi quia quo doloremque est totam. Quo recusandae recusandae est architecto distinctio necessitatibus ut. Dignissimos deleniti placeat eum rerum eum ea. Quia eaque ipsum et maxime. Sint quia beatae dolor repellat aperiam. Perspiciatis recusandae perferendis dolore ut.",
          published: 0,
          date_publication: "2023-02-23 16:27:17",
          likes: 934,
          dislikes: 700,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 21,
            name: "fugiat",
            parent_id: 4,
          },
        },
        {
          id: 46,
          category_id: 1,
          title: "Rerum.",
          description: "Fugiat et.",
          content:
            "Neque veniam molestiae molestiae eaque error dolorum. Optio officiis voluptas et voluptatibus et. Dolorem voluptatem inventore est accusantium temporibus sit sapiente.",
          published: 0,
          date_publication: "2023-02-23 16:27:17",
          likes: 611,
          dislikes: 226,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
        {
          id: 47,
          category_id: 23,
          title: "Ad quasi.",
          description: "Cumque sequi quae.",
          content:
            "Eius maxime delectus alias repudiandae ut laborum. Eligendi rerum aspernatur ipsum consequatur voluptatem. Ipsam ex sint illum aut maiores voluptas. Rerum consequatur blanditiis at provident dolorem voluptas. Iste alias natus sed temporibus exercitationem sapiente. Totam ut nihil nobis rem ab maiores labore sit. Vel voluptatem et iste. Quasi officia dolor non odio in facilis ut.",
          published: 0,
          date_publication: "2023-03-05 16:27:17",
          likes: 941,
          dislikes: 573,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 23,
            name: "nesciunt",
            parent_id: 5,
          },
        },
        {
          id: 48,
          category_id: 21,
          title: "Iste.",
          description: "Repellat et.",
          content:
            "Expedita omnis fugit accusantium sit accusantium commodi impedit. Fugiat dignissimos explicabo amet deserunt fugit. Quo temporibus cupiditate necessitatibus eius modi architecto eum. Dolor quasi distinctio accusamus commodi enim adipisci.",
          published: 0,
          date_publication: "2023-03-07 16:27:17",
          likes: 681,
          dislikes: 198,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 21,
            name: "fugiat",
            parent_id: 4,
          },
        },
        {
          id: 49,
          category_id: 18,
          title: "Ut.",
          description: "Dignissimos dolorem.",
          content:
            "Dolores placeat voluptatum ut modi fuga. Necessitatibus occaecati et doloribus nisi. Fugit quis est facilis ut debitis. Est ipsum quia amet nesciunt amet.",
          published: 1,
          date_publication: "2023-02-26 16:27:17",
          likes: 650,
          dislikes: 568,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 18,
            name: "expedita",
            parent_id: 4,
          },
        },
        {
          id: 50,
          category_id: 1,
          title: "Culpa.",
          description: "Odit veritatis.",
          content:
            "Nulla facere doloremque aliquid placeat amet. Eum atque repudiandae vel itaque quia et. Assumenda dolores soluta dignissimos illo. Velit ut in sed officiis qui blanditiis suscipit. Sunt praesentium voluptatibus harum autem et. Sit et magnam officia deserunt voluptatem magnam. Nobis vitae dolor adipisci pariatur et nostrum error. Earum fugiat qui quo natus quia qui ab.",
          published: 1,
          date_publication: "2023-02-22 16:27:17",
          likes: 1000,
          dislikes: 364,
          created_at: "2023-02-21T14:27:17.000000Z",
          updated_at: "2023-02-21T14:27:17.000000Z",
          category: {
            id: 1,
            name: "totam",
            parent_id: null,
          },
        },
      ],
    };
  },
  components: { BPostItem },
};
</script>

<style scoped></style>